include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    sort_child_properties_last: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore
